### ISSUE TITLE
Type Mapping and Analyzer

### ISSUE THREAD

**Issue by jubayerarefin** [gtkvn/larasearch#2]
Hi Kenshin, hope you are doing fine. Is there any way I can set field type and analyzer for a Model field ?

**Comment by cuonggt** [comment]
Hi, could you explain more about type mapping and analyzer for a model field?

**Comment by jubayerarefin** [comment]
I meant is it possible to define the mapping and analyzers inside a Model file ?

> protected $mappingProperties = array(
   'title' => array(
        'type' => 'string',
        'analyzer' => 'standard'
    )
);

Further reference: https://github.com/elasticquent/Elasticquent

**Comment by cuonggt** [comment]
No, temporary it doesn't support to define them inside a Model file. You should use raw query for passing those mapping properties like the following:

$orders = App\Order::search(['query' => ['match' => ['title' => 'Star Trek']]])->get();

Reference: https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_index_management_operations.html

**Comment by cuonggt** [comment]
Whoops, seem I misunderstand this issue. Let me check it again and feed back later!

**Comment by jubayerarefin** [comment]
Got any solution yet ?

**Comment by jubayerarefin** [comment]
I have found a solution for my problem.
