### ISSUE TITLE
 ClearCommand is (still) Missing  

### ISSUE THREAD

**Issue by sevmardi** [gtkvn/larasearch#5]
Hi! 

```
php artisan

``` 
Is complaining

```
Class Gtk\Larasearch\Console\ClearCommand does not exist 

```

Did some digging and found out that there is no ClearCommand class in console folder! ?? Am I the only one here?

**Comment by jubayerarefin** [comment]
@sevmardi It was changed to `FlushCommand`. reference: #3

**Comment by mouhsinelonly** [comment]
yep the error still exist

**Comment by jubayerarefin** [comment]
@mouhsinelonly you can use 1.1.3 to avoid that
